# Generated by Django 3.2.11 on 2024-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
