# Generated by Django 3.2.11 on 2024-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usermodel_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('М', 'Муж.'), ('Ж', 'Жен.')], max_length=10),
        ),
    ]
